[package]
name = "all_goes"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.7.2"
fast-float = "0.2.0"
fast-str = "1.0.0"
memmap2 = "0.9.5"
rayon = "1.10.0"
rustc-hash = "2.0.0"

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"
